### ISSUE TITLE
parsing chinese character damage wrong

### ISSUE THREAD

**Issue by waterj** [shagu/ShaguDPS#10]
if some character named 你的某某 does damage, it will be treated as player's damage

**Comment by shagu** [comment]
Since everything in vanilla are text-based combat scans, I don't think there's a way to distinguish between that and a playername. There are simply no meta-information in the combat log beside the text itself.

It's also near impossible to me to work  on a client I can't understand while doing text-comparisons with strings from which I'm not able to read a single character.

If anyone wants to take a look, please do it. If nobody coming up with a solution for it, I'll continue considering it impossible to fix and might close that ticket at any time the next years without a comment.
