### ISSUE TITLE
Pet reflect damage not tracked

### ISSUE THREAD

**Issue by Aegael** [shagu/ShaguDPS#8]
If a warlock/hunter pet has something like Thorns on them, the damage isn't tracked. Would it be possible to change that?

**Comment by shagu** [comment]
Should be fixed via: https://github.com/shagu/ShaguDPS/commit/c7f80cc0dfc741b51f2d2fb21e73f4f2b5d7eff5 and https://github.com/shagu/ShaguDPS/commit/df9f98a238908b72ceac8450331caf6bac74dd63

Requires [SuperWoW](https://github.com/balakethelock/SuperWoW) to work, because the original vanilla client does not show the required information in combat log.
