### ISSUE TITLE
Totems not integrated

### ISSUE THREAD

**Issue by Bestoriop** [shagu/ShaguDPS#9]
Hey, currently totems aren't displayed in the view.

It would be great to add a line for each totem which does damage or healing : 
- Searing Totem
- Magma Totem
- Fire Nova Totem
- Healing Stream Totem

If multiple shamans use totems, the data will sum the damage. 

Totem's names aren't linked to their owner in the combat log so you can't link them as pets, but adding a line for each totem is a good compromise.

**Comment by shagu** [comment]
Fixed via: https://github.com/shagu/ShaguDPS/commit/c7f80cc0dfc741b51f2d2fb21e73f4f2b5d7eff5 and https://github.com/shagu/ShaguDPS/commit/df9f98a238908b72ceac8450331caf6bac74dd63

Requires [SuperWoW](https://github.com/balakethelock/SuperWoW) to work, because the original vanilla client does not show the required information in combat log.
